# Generated by Django 5.2.8 on 2025-12-17 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0004_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
