# Generated by Django 5.2.8 on 2025-12-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0005_alter_twit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
