# Generated by Django 5.2.8 on 2025-12-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0007_comment_share_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
